### ISSUE TITLE
When is it activated?

### ISSUE THREAD

**Issue by cjdduarte** [xquercus/load-balanced-scheduler#3]
Example: Today I have 130 cards to review, 80 cards in learning (steps 15 1440 4320) and I will study 90 new cards.

Does it redistribute according to the study or does the analysis after finishing all above?

Another question, are these learning cards (steps 15 1440 4320) affected? Because I use these steps (1440 (1 day) 4320 (3 days) as a filter of what I actually learned.

**Comment by xquercus** [comment]
Cards are balanced when they are scheduled -- right after pressing the
hard, normal, or easy button.

**Comment by cjdduarte** [comment]
Another question, are these learning cards (steps 15 1440 4320) affected? Because I use these steps (1440 (1 day) 4320 (3 days) as a filter of what I actually learned.

**Comment by xquercus** [comment]
No, learning steps aren't affected.  Only review cards and card that graduate from learning to review are load balanced.

As an aside, I believe anki adds random fuzz to learning cards as well.  I've been told as much as 25% under the old scheduler but less under the experimental scheduler.
