### ISSUE TITLE
using decks and subdecks

### ISSUE THREAD

**Issue by cjdduarte** [xquercus/load-balanced-scheduler#4]
In Anki 2.1 I started to use subdecks (4 tree levels) because the new algorithm randomizes everything.

If I study at the level of a subdeck, will the addon balancing at the total level of cards on the parent deck or will it look at the level of the subdecks?

**Comment by xquercus** [comment]
The algorithm looks at the total number of due cards when load balancing.

**Comment by cjdduarte** [comment]
Tanks

**Comment by cjdduarte** [comment]
Tanks
