### ISSUE TITLE
filtered deck does not work

### ISSUE THREAD

**Issue by cjdduarte** [xquercus/load-balanced-scheduler#5]
Today I had to anticipate the 1 day reviews and used the filtered deck functionality. I've had many cards answered, scheduled for 20 days from now. See that he has not rebalanced.

Using Anki 2.1 v2 scheduler enabled.

![screenshot_1](https://user-images.githubusercontent.com/42243532/48165344-67f33d00-e2cc-11e8-993d-f395e0e770b2.png)

**Comment by xquercus** [comment]
Thank you for the report.  I'll look into this.  Is there any chance you could screenshot the list of plugins you have installed and the configuration of the filtered deck?

**Comment by cjdduarte** [comment]
I use your addon for several weeks. I never had a problem. It works perfectly. Just today, when it was the first time I used a filtered deck, that was when it happened.

The filtered deck was created from this option:
![image](https://user-images.githubusercontent.com/42243532/48167271-5ad94c80-e2d2-11e8-95e1-126354db6cd5.png)

My addons:
![image](https://user-images.githubusercontent.com/42243532/48167198-1ea5ec00-e2d2-11e8-85b6-7008b3876649.png)

**Comment by lovac42** [comment]
num_cards = self.col.db.scalar("""select count() from cards where **due = ?** and queue = 2""", self.today + check_ivl)

filtered decks use card.**odue** when rescheduling is turned on. So you end up stacking everything on one day as that is the lowest day reported.

**Comment by cjdduarte** [comment]
I understood, but is it possible to correct myself? Or is it outside the purpose of the addon?

**Comment by xquercus** [comment]
Thank you both for reporting **and** proposing a solution to this.  I really appreciate these reports.  I **think** this looks like a bug.  That is the add-on should work in this situation.  I'll try and turn around a tested fix in the next few days.

**Comment by cjdduarte** [comment]
Thank you.

**Comment by xquercus** [comment]
So here's the deal.  It turns out Anki (surprisingly) doesn't call the function we patch to load balance so we don't even have the opportunity to do so.  No doubt it could be implemented but it's not something I'd be interested in implementing or maintaining.  More patches just increase the likelihood of introducing bugs or an incompatibility when Damien changes the scheduler code.  It's surprising because normally review cards are fuzzed and hence load balanced.  This seems to be an exception.

This will get documented in the README.

**Comment by cjdduarte** [comment]
Thank you. I'm going to open a call to Damien for him to evaluate that. This may be an Anki bug. Or not.

**Comment by cjdduarte** [comment]
Hi, Damien asked to technically detail the problem (function that may have the problem). Can you explain?

**Comment by xquercus** [comment]
Just wanted to thank you guys for fleshing this out.  I'm currently going on no sleep with altitude sickness but it looks like you guys are rocking.

**Comment by cjdduarte** [comment]
I will close this call, because I decided not to use more filtered decks

**Comment by thiswillbeyourgithub** [comment]
I would be very interested in this feature, V2 scheduler won't change much for a while IMO and you can always specify up to which version of anki should your addon be working or automatically disabled.

The V2 scheduler makes filtered decks way more practical and appealing, so I think there's a growing need for load balancing with them.

Thanks for considering this. Have a nice day.
