### ISSUE TITLE
Pseudorandomness ivl

### ISSUE THREAD

**Issue by cjdduarte** [xquercus/load-balanced-scheduler#6]
I noticed that the range of ivl in the addon when it is the same or is starting, the addon will always fill from the highest to the lowest ivl, leaving for these cases pseudorandomness.

![image](https://user-images.githubusercontent.com/42243532/49365933-30ab5c80-f6cf-11e8-9baa-de42a7122154.png)

It is suggested to implement a random list instead of the range.

![image](https://user-images.githubusercontent.com/42243532/49366059-7ec06000-f6cf-11e8-8df9-a651f60e9981.png)

**Comment by cjdduarte** [comment]
Hi?

**Comment by csmith1210** [comment]
So I took a look at the code before starting to use this addon myself, and I thought I would clarify this for people coming here with the same question.

First, the addon never claims to randomly fill days with cards, just that Anki itself assigns a random interval for the review based on card ease and its algorithm. The addon then checks this assigned interval for the day that has the least cards due on it and places the review on that day.

Here's the relevant code in that for block:
```if num_cards <= min_num_cards:
            best_ivl = check_ivl
            log_debug("> ")
min_num_cards = num_cards`

The reason for the behavior you're noticing is primarily because that high end of the interval range returned by Anki is the most likely day with the least amount of cards due.

**Comment by galantra** [comment]
@cjdduarte Do you have a suggestion how to change the code to apply a random list?
